# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vulndork_gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog

class Ui_mainframe(object):
    def setupUi(self, mainframe):
        mainframe.setObjectName("mainframe")
        mainframe.resize(472, 690)
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        mainframe.setFont(font)
        mainframe.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        mainframe.setStyleSheet("alternate-background-color: rgb(164, 0, 0);\n"
"border-color: rgb(164, 0, 0);")
        self.line = QtWidgets.QFrame(mainframe)
        self.line.setGeometry(QtCore.QRect(10, 50, 451, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(mainframe)
        self.line_2.setGeometry(QtCore.QRect(10, 625, 451, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.dns_file = QtWidgets.QFrame(mainframe)
        self.dns_file.setGeometry(QtCore.QRect(10, 90, 451, 61))
        self.dns_file.setStyleSheet("")
        self.dns_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dns_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dns_file.setObjectName("dns_file")
        self.label = QtWidgets.QLabel(self.dns_file)
        self.label.setGeometry(QtCore.QRect(4, 10, 191, 41))
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.dns_file)
        self.lineEdit.setGeometry(QtCore.QRect(207, 20, 181, 21))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.browse1 = QtWidgets.QToolButton(self.dns_file)
        self.browse1.setGeometry(QtCore.QRect(395, 21, 41, 20))
        self.browse1.setObjectName("browse1")
        self.browse1.clicked.connect(self.browsefiles)
        self.label_3 = QtWidgets.QLabel(mainframe)
        self.label_3.setGeometry(QtCore.QRect(17, 15, 161, 31))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(mainframe)
        self.pushButton.setGeometry(QtCore.QRect(98, 533, 261, 25))
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(mainframe)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 481, 71))
        self.label_4.setStyleSheet("background-color: rgb(164, 0, 0);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(mainframe)
        self.label_5.setGeometry(QtCore.QRect(0, 620, 481, 71))
        self.label_5.setStyleSheet("background-color: rgb(164, 0, 0);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(mainframe)
        self.label_6.setGeometry(QtCore.QRect(154, 653, 151, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(mainframe)
        self.label_7.setGeometry(QtCore.QRect(80, 80, 67, 17))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.output = QtWidgets.QListView(mainframe)
        self.output.setGeometry(QtCore.QRect(10, 250, 451, 261))
        self.output.setObjectName("output")
        self.label_8 = QtWidgets.QLabel(mainframe)
        self.label_8.setGeometry(QtCore.QRect(231, 28, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.dorks_path = QtWidgets.QFrame(mainframe)
        self.dorks_path.setGeometry(QtCore.QRect(10, 170, 451, 61))
        self.dorks_path.setStyleSheet("")
        self.dorks_path.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dorks_path.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dorks_path.setObjectName("dorks_path")
        self.label_9 = QtWidgets.QLabel(self.dorks_path)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 161, 41))
        self.label_9.setTextFormat(QtCore.Qt.RichText)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.dorks_path)
        self.lineEdit_2.setGeometry(QtCore.QRect(207, 20, 181, 21))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.browse2 = QtWidgets.QToolButton(self.dorks_path)
        self.browse2.setGeometry(QtCore.QRect(395, 20, 41, 20))
        self.browse2.setObjectName("browse2")
        self.progressBar = QtWidgets.QProgressBar(mainframe)
        self.progressBar.setGeometry(QtCore.QRect(42, 579, 391, 21))
        font = QtGui.QFont()
        font.setFamily("Umpush")
        font.setPointSize(10)
        self.progressBar.setFont(font)
        self.progressBar.setToolTipDuration(-1)
        self.progressBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.progressBar.setStyleSheet("alternate-background-color: rgb(164, 0, 0);")
        self.progressBar.setMinimum(0)
        self.progressBar.setProperty("value", 9)
        self.progressBar.setObjectName("progressBar")
        self.label_5.raise_()
        self.label_4.raise_()
        self.dns_file.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.label_3.raise_()
        self.pushButton.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.output.raise_()
        self.label_8.raise_()
        self.dorks_path.raise_()
        self.progressBar.raise_()

        self.retranslateUi(mainframe)
        QtCore.QMetaObject.connectSlotsByName(mainframe)

    def browsefiles(self):
        fname = QFileDialog.getOpenFileName(self.QtWidgets, 'Open file', '/home/cymed/Desktop/my_vulndork/vulndork')
        self.filename.setText(fname[0])

    def retranslateUi(self, mainframe):
        _translate = QtCore.QCoreApplication.translate
        mainframe.setWindowTitle(_translate("mainframe", "vulndork"))
        self.label.setText(_translate("mainframe", "Enter hospitals DNS file:"))
        self.browse1.setText(_translate("mainframe", "..."))
        self.label_3.setText(_translate("mainframe", "<html><head/><body><p><img src=\":/newPrefix/Webp.net-resizeimage(1).png\"/></p></body></html>"))
        self.pushButton.setText(_translate("mainframe", "Start the scan"))
        self.label_6.setText(_translate("mainframe", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-style:italic; color:#ffffff;\">Copyright © CYMED 2021</span></p></body></html>"))
        self.label_8.setText(_translate("mainframe", "<html><head/><body><p><span style=\" font-size:12pt; color:#ffffff;\">Passive vulnerability scanner</span></p></body></html>"))
        self.label_9.setText(_translate("mainframe", "Select dorks file path:"))
        self.browse2.setText(_translate("mainframe", "..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainframe = QtWidgets.QDialog()
    ui = Ui_mainframe()
    ui.setupUi(mainframe)
    mainframe.show()
    sys.exit(app.exec_())
